"""
Django settings for db_analyzer project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import logging.config
from pathlib import Path
import os
from apscheduler.schedulers.background import BackgroundScheduler
from django.utils.http import urlquote

from db_analyzer.model.sql_model import SQL_Model
from db_analyzer.model.yaml_model import Yaml_Model


ENV_YAML = Yaml_Model()
MYSQL_CFG = ENV_YAML.read_node('env.yaml', 'mysql')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # 配置文件及代码路径


logging.config.fileConfig(os.path.join(BASE_DIR, 'logging.conf'))
LOGGER = logging.getLogger('root')
MYSQL_URL = 'mysql+pymysql://' + MYSQL_CFG['username'] + ':' + urlquote(str(MYSQL_CFG['password'])) + '@' + \
               MYSQL_CFG['host'] + ':' + str(MYSQL_CFG['port']) + '/' + MYSQL_CFG['database'] + '?charset=utf8'

SQL_CONNECTION = SQL_Model(MYSQL_URL)
CON_TEST = SQL_Model(MYSQL_URL)

FLAG_FIX = 0  # 标记是否在进入任务执行前有需要对apscheduler_jobs_info表进行数据修复 0:无需修复 1:需要修复

SCHEDULER = BackgroundScheduler({

    'apscheduler.jobstores.default': {
        'type': 'sqlalchemy',
        'url': MYSQL_URL
    },

    'apscheduler.executors.default': {
        'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
        'max_workers': '200'
    },

    'apscheduler.executors.processpool': {
        'type': 'processpool',
        'max_workers': '200'
    },

    'apscheduler.job_defaults.coalesce': 'true',
    'apscheduler.job_defaults.max_instances': '1',
    'apscheduler.timezone': 'Asia/Shanghai',  # 设置时区　，存储桶时区
})

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6ckvc@djt0crag0fg#(6!j=#1=u*#f5r^u439=rqu*9*24az6f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'db_analyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'db_analyzer.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
